FROM ubuntu:16.04

# System packages
RUN apt-get update && apt-get install -y \
    gdb \
    valgrind \
    unzip \
    git \
    emacs \
    htop \
    bash-completion \
    automake \
    libtool \
    pkg-config \
    g++ \
    wget \
    clang \
    clang-format \
    aptitude \
    cmake \
    cmake-curses-gui \
    cmake-extras \
    extra-cmake-modules

# Bitcoin dependencies
RUN apt-get install -y \
    libdb-dev \
    libdb++-dev \
    libqt5gui5 \
    qtbase5-dev \
    libboost-all-dev \
    bsdmainutils \
    libssl-dev \
    libevent-dev

# Python3 and virtualenv
RUN apt-get install -y \
    python3 \
    python3-pip \
    libpng-dev \
    libpng++-dev \
    python3-crypto-dbg \
    python-crypto-doc \
    python-cryptography-doc \
    python3-cryptography-vectors \
    python-dbus-doc \
    python3-dbus-dbg \
    python-secretstorage-doc \
    python-setuptools-doc

RUN apt-get install -y \
    software-properties-common

# Python3 virtualenvwrapper
RUN pip3 install --upgrade pip setuptools
RUN pip3 install virtualenvwrapper

# matplotlib numpy
RUN apt-get install -y \
    libfreetype6-dev \
    libjpeg-dev \
    libopenblas-dev

COPY install_virtualenvwrapper.sh /tmp/
RUN /bin/bash -c "/tmp/install_virtualenvwrapper.sh"

# Utilities
RUN apt-get install -y \
    netcat \
    net-tools \
    iputils-ping

RUN groupadd --gid 1002 dcrunner
RUN useradd -d /home/dcrunner --uid 1002 -m --gid 1002 dcrunner

RUN echo "" >> /home/dcrunner/.bashrc
RUN echo "export WORKON_HOME=/home/dcrunner/py_virtual_env" >> /home/dcrunner/.bashrc
RUN echo "export VIRTUALENVWRAPPER_PYTHON=`which python3`" >> /home/dcrunner/.bashrc
RUN echo "source /usr/local/bin/virtualenvwrapper.sh" >> /home/dcrunner/.bashrc
RUN echo "workon dc-dev" >> /home/dcrunner/.bashrc

# https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
COPY entrypoint.sh /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]
