FROM ppc64le/ubuntu:16.04

# System packages
RUN apt-get update && apt-get install -y \
    gdb \
    valgrind \
    unzip \
    git \
    emacs \
    htop \
    bash-completion \
    automake \
    libtool \
    pkg-config \
    g++ \
    wget \
    clang \
    clang-format \
    aptitude \
    libboost-all-dev \
    cmake \
    cmake-curses-gui \
    cmake-extras \
    extra-cmake-modules

# SSL
RUN apt-get install -y \
    libssl-dev \
    libssl1.0.0-dbg

# Python3 and virtualenv
RUN apt-get install -y \
    python3 \
    python3-pip \
    libpng-dev \
    libpng++-dev \
    python3-crypto-dbg \
    python-crypto-doc \
    python-cryptography-doc \
    python3-cryptography-vectors \
    python-dbus-doc \
    python3-dbus-dbg \
    python-secretstorage-doc \
    python-setuptools-doc

# ZeroMQ
RUN apt-get install -y \
    libzmqpp-dev \
    libzmq5-dbg \
    libsodium-dev \
    libsodium-dbg \
    python-zmq \
    python3-zmq

RUN apt-get install -y \
    software-properties-common

# Package management (for Power Repos)
RUN apt-get install -y \
    software-properties-common

# Add POWER repo and import key
RUN apt-add-repository "deb http://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/ xenial main"
RUN wget -q http://public.dhe.ibm.com/software/server/POWER/Linux/xl-compiler/eval/ppc64le/ubuntu/public.gpg -O- | apt-key add -

# The package maintainer decided to put the version in the package name,
# so the package name changes with version updates. Awesome.
RUN apt-get install -y `apt-cache search libxlmass | awk '{print $1}'`

# Optimized linear algebra
RUN wget https://sourceforge.net/projects/math-atlas/files/Developer%20%28unstable%29/3.11.39/atlas3.11.39.tar.bz2/download --output-document=atlas3.11.39.tar.bz2

# matplotlib numpy
RUN apt-get install -y \
    libfreetype6-dev \
    libjpeg-dev \
    libopenblas-dev

# Python3 virtualenvwrapper
RUN pip3 install --upgrade pip setuptools
RUN pip3 install virtualenvwrapper --ignore-installed six
COPY install_virtualenvwrapper.sh /tmp/
RUN /bin/bash -c "/tmp/install_virtualenvwrapper.sh"

# Utilities
RUN apt-get install -y \
    netcat \
    net-tools \
    iputils-ping \
    telnet

RUN apt-get install -y sudo

# Cleanup
RUN apt-get clean autoclean

RUN groupadd --gid 1002 dcrunner
RUN useradd -d /home/dcrunner --uid 1002 -m --gid 1002 dcrunner
COPY bashrc /home/dcrunner/.bashrc

EXPOSE 55556
RUN echo "dcrunner ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

#USER dcrunner

#COPY install_virtualenvwrapper.sh /tmp/
#RUN /bin/bash -c "/tmp/install_virtualenvwrapper.sh"

#USER root

# https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
COPY entrypoint.sh /tmp/entrypoint.sh
ENTRYPOINT ["/tmp/entrypoint.sh"]
